= basex-gradle-starter
:toc:
:shadowJarName: basex-gradle-starter-1.0.jar
:basexVersion: 8.1.1

A simple build script template for using http://basex.org[BaseX] with Gradle.
Also adds Saxon HE so you can use XSLT 2.0 and 3.0 out of the gate.

This is version {basexVersion} if you want to test with a different version then
choose one of the other branches (only from 8.0 onwards).

Installation steps:

1. `git clone https://github.com/xokomola/basex-gradle-starter.git`

Yep, that's right. There's only one step between cloning this and running
queries with BaseX. It even installs Gradle for you.

For more information on https://gradle.org[Gradle] have a look at it's extensive
documentation.

== Startup tasks

Most of the familiar startup scripts are all available as tasks:

- `gui`
- `repl`
- `server`, or `serverstart` and `serverstop`
- `http`, or `httpstart` and `httpstop`

Configuration of BaseX is done in `gradle.properties`.

== Where to put XQuery code?

For now the assumes that both source and tests are in `webapp` (or wherever you
point `org.basex.WEBPATH` property in `gradle.properties` to).

== Tests

.Using the REPL

To run tests you can start the REPL and call the test command with the path to
the directory that contains the tests.

[source]
----
.\repl
> TEST test
----

.Using the test task

To run all tests, or to run tests from another test directory.

[source]
----
.\gradlew test
.\gradlew test -Pdir=testdir
----

.Continuous

To run the tests from a directory continuously add the `--continuous` flag.

[source]
----
gradlew test -Pdir=test --continuous
----

Note that using this option requires the use of an explicit test directory
argument.


== DBA module

The DBA module allows administration on BaseX via a nice web interface.

[source]
----
.\gradlew httpstart
start http://localhost:8984/dba
----

== Building

=== shadowJar

You can combine all the needed jar files and create a so-called fat jar. This
allows you to run BaseX as a jar (easy to deploy). You can already do that
with the BaseX core distribution but with this it also includes the optional
libraries.

[source]
----
.\gradlew shadowJar
----

The jar file will be created in the `build/libs` directory.

This wil not contain the `data`, `repo` and `webapp` directories, you will have
to pass the paths (and possibly other settings). In this case I pass the paths
to the project files.

.Run HTTP server from jar
[source,subs="attributes"]
----
java -Dorg.basex.dbpath=data
     -Dorg.basex.repopath=repo 
     -Dorg.basex.webpath=webapp
     -jar build/libs/{shadowJarName}
----

You can also use all the regular basex
http://docs.basex.org/wiki/Command-Line_Options[command-line arguments]. For
example start the HTTP server on a different port.

[source,subs="attributes"]
----
java -Dorg.basex.dbpath=data
     -Dorg.basex.repopath=repo 
     -Dorg.basex.webpath=web
     -jar build/libs/{shadowJarName}
     -h1234
----

You can connect to this server (from another shell window).

.Start the REPL
[source,subs="attributes"]
----
java -cp build/libs/{shadowJarName} org.basex.BaseXClient
----

Or, start the GUI client.

.Start the GUI
[source,subs="attributes"]
----
java -cp build/libs/{shadowJarName} org.basex.BaseXGUI
----

== Contributors

- https://github.com/xokomola[xokomola]
- https://github.com/vincentml[vincentml]
