= basex-gradle-starter
:toc:
:shadowJarName: basex-gradle-starter-all.jar
:basexVersion: 9.1.2

A simple build script template for using http://basex.org[BaseX] from a
https://gradle.org[Gradle] buildscript (also adds Saxon HE).

This is for BaseX version {basexVersion} if you want to test with a different version then
choose one of the other branches.

Installation steps:

1. `git clone https://github.com/xokomola/basex-gradle-starter.git`
2. There is no step 2

That's right. There's just one step between cloning this and running
queries with BaseX.

== Startup tasks

This build script provides the following tasks for running BaseX.

- `gui`
- `http`

Configuration is done in `gradle.properties`.

== Standalone JAR

You can combine all the needed jar files and create a so-called fat JAR. This
allows you to run BaseX as a JAR (easy to deploy). You can already do that
with the BaseX core distribution but with this it also includes the optional
libraries.

[source]
----
gradlew shadowJar
----

The JAR file will be created in the `build/libs` directory.

This wil not contain the `data`, `repo` and `webapp` directories, you will have
to pass the paths (and possibly other settings). In this case I pass the paths
to the project files.

.Run HTTP server from JAR
[source,subs="attributes"]
----
java -Dorg.basex.dbpath=data
     -Dorg.basex.repopath=repo 
     -Dorg.basex.webpath=webapp
     -jar build/libs/{shadowJarName}
----

You can also use all the regular basex
http://docs.basex.org/wiki/Command-Line_Options[command-line arguments]. For
example start the HTTP server on a different port.
You can connect to this server (from another shell window).

.Start the REPL
[source,subs="attributes"]
----
java -cp build/libs/{shadowJarName} org.basex.BaseXClient
----

Or, start the GUI client.

.Start the GUI
[source,subs="attributes"]
----
java -cp build/libs/{shadowJarName} org.basex.BaseXGUI
----

== Contributors

- https://github.com/xokomola[xokomola]
- https://github.com/vincentml[vincentml]
